/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exform;

import Connection.DBConnection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author RizkyHermawan
 */
public class Create extends javax.swing.JFrame {

    private PreparedStatement ps;
    private Connection koneksi;
    private ResultSet rs;

    /**
     * Creates new form Create
     */
    public Create() {
        initComponents();
        setLocationRelativeTo(this);
        koneksi = DBConnection.DB();
        backCreate1.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backCreate1 = new background.backCreate();
        texidkaryawan = new javax.swing.JTextField();
        btncreate = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        texpassword = new javax.swing.JPasswordField();
        texconfirm = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(700, 400));

        texidkaryawan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        texidkaryawan.setForeground(new java.awt.Color(102, 102, 102));
        texidkaryawan.setText("ID Karyawan");
        texidkaryawan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                texidkaryawanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                texidkaryawanFocusLost(evt);
            }
        });

        btncreate.setBackground(new java.awt.Color(0, 102, 204));
        btncreate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btncreate.setText("Create");
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });

        btncancel.setBackground(new java.awt.Color(0, 102, 204));
        btncancel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btncancel.setText("Cancel");

        texpassword.setText("Password");
        texpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                texpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                texpasswordFocusLost(evt);
            }
        });

        texconfirm.setText("Password");
        texconfirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                texconfirmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                texconfirmFocusLost(evt);
            }
        });

        javax.swing.GroupLayout backCreate1Layout = new javax.swing.GroupLayout(backCreate1);
        backCreate1.setLayout(backCreate1Layout);
        backCreate1Layout.setHorizontalGroup(
            backCreate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backCreate1Layout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addGroup(backCreate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backCreate1Layout.createSequentialGroup()
                        .addComponent(btncreate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backCreate1Layout.createSequentialGroup()
                        .addGroup(backCreate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texidkaryawan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texpassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texconfirm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(135, 135, 135))))
        );
        backCreate1Layout.setVerticalGroup(
            backCreate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backCreate1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(texidkaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(texpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(texconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(backCreate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncreate)
                    .addComponent(btncancel))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backCreate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backCreate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cekconfirmpassword() {
        String id = texidkaryawan.getText();
        String pass = texpassword.getText();
        String confirm = texconfirm.getText();
        String sql = "select * from karyawan where id_karyawan = '" + id + "'";
        if (pass.equals("Password")) {
            texpassword.setForeground(Color.red);
        } else if (pass.equals(confirm)) {
            try {
                ps = koneksi.prepareStatement(sql);
                rs = ps.executeQuery(sql);
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Same");
                } else if (!(rs.next())) {
                    JOptionPane.showMessageDialog(null, "ID Karyawan tidak ditemukan");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Connection Lose");
            }
        } else if (!(pass.equals(confirm))) {
            texconfirm.setForeground(Color.red);
        }
    }

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
        // TODO add your handling code here
        cekconfirmpassword();
    }//GEN-LAST:event_btncreateActionPerformed

    private void texidkaryawanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_texidkaryawanFocusGained
        // TODO add your handling code here:
        if ("ID Karyawan".equals(texidkaryawan.getText())) {
            texidkaryawan.setText("");
        }
        texidkaryawan.setForeground(Color.black);
    }//GEN-LAST:event_texidkaryawanFocusGained

    private void texidkaryawanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_texidkaryawanFocusLost
        // TODO add your handling code here:
        if ("".equals(texidkaryawan.getText())) {
            texidkaryawan.setText("ID Karyawan");
        }
        texidkaryawan.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_texidkaryawanFocusLost

    private void texconfirmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_texconfirmFocusGained
        // TODO add your handling code here:
        if (texconfirm.getForeground().equals(Color.red)) {
            texconfirm.setText("");
            texconfirm.setForeground(Color.black);
        } else if ("Password".equals(texconfirm.getText())) {
            texconfirm.setText("");
            texconfirm.setForeground(Color.black);
        }
    }//GEN-LAST:event_texconfirmFocusGained

    private void texconfirmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_texconfirmFocusLost
        // TODO add your handling code here:
        if ("".equals(texconfirm.getText())) {
            texconfirm.setText("Password");
        }
    }//GEN-LAST:event_texconfirmFocusLost

    private void texpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_texpasswordFocusGained
        // TODO add your handling code here:
        if(texpassword.getForeground().equals(Color.red)){
            texpassword.setForeground(Color.black);
            texpassword.setText("");
        }else if ("Password".equals(texpassword.getText())) {
            texpassword.setText("");
            texpassword.setForeground(Color.black);
        }
    }//GEN-LAST:event_texpasswordFocusGained

    private void texpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_texpasswordFocusLost
        // TODO add your handling code here:
        if ("".equals(texpassword.getText())) {
            texpassword.setText("Password");
            texpassword.setForeground(Color.black);
        }
    }//GEN-LAST:event_texpasswordFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private background.backCreate backCreate1;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btncreate;
    private javax.swing.JPasswordField texconfirm;
    private javax.swing.JTextField texidkaryawan;
    private javax.swing.JPasswordField texpassword;
    // End of variables declaration//GEN-END:variables
}
